### ISSUE TITLE
New Peach

### ISSUE THREAD

**Issue by CFXd** [davidosomething/grunt-peach#1]
@davidosomething,

Just wanted to point out that [Peach](https://github.com/petesaia/Peach) was [updated ](https://github.com/petesaia/Peach/commit/d300f2f1c9d7381ee90aafbd2e2802e62105c0ea). Would love to see an update here too but I'm not enough of a JS maestro to submit a PR myself.

Thanks!

**Comment by davidosomething** [comment]
Done -- new version 0.1.0 published
https://www.npmjs.com/package/grunt-peach

**Comment by CFXd** [comment]
Thank you so much! :+1:
