### ISSUE TITLE
Cannot find module 'PeachTests/assets/js/peach'

### ISSUE THREAD

**Issue by joakimcarlsten** [davidosomething/grunt-peach#3]
Hi, When I try using this grunt task I get an `>> Error: Cannot find module 'PeachTests/assets/js/peach'`.
Since I don't know that much about grunt tasks I am not able to solve this by myself.

It seems however to come from tasks/peach.coffee and the line `Peach = require 'PeachTests/assets/js/peach'`
I cannot figure out what this line is referring to. Has something changed at the petesaia/Peach-repo?

If you could help me with this it would be greatly appreciated.
Thanks for a great module!
Kind regards
Joakim

**Comment by davidosomething** [comment]
Just pushed 1.0.0 -- the repository this package depends on was updated (and isn't in NPM)
try it out and let me know if it is working for you

**Comment by joakimcarlsten** [comment]
Many thanks!

Now it is working.

/Joakim
